public class Main {

    public static void main(String[] args) {

        TextTools textTools = new TextTools();
        Vigenere vigenere = new Vigenere();
        FriedmannTest friedmannTest = new FriedmannTest();
        KasiskiTest kasiskiTest = new KasiskiTest();
        Caesar caesar = new Caesar();

        String password = "MORPHEUS";
        String clearText = "Ach, wie schön, dass niemand weiß, dass ich Rumpelstielzchen heiß";
        String secret = "KFEKWIFHZBJRTUBOWRIMHBTUOOJAXIUBVNTFWYCWEDZFHJTCPVSORSZSANVNBFDLPNFKAYSIYOXPYWMWBLSOUJISWSLXEKQMMWTUZVUUGBZDHJNWWWQMKFXIQIQVTUDJEIHEXIZFYHTUZYFZXTKFCCZSPMNEFKAYSCDEXQFTTFVNVLHJKFWYCQCULTHJBYDDRXUQEEXOSKHGMWMWQJGYSXMOQWNNHENZFOLLNGAYKFCCZSNERZEIMWFHHPVSCPXIXACUCWNALIQXRDTSRDEKWAWGUUGBOTXPXZTUZQVSFOCOQGNNURTFZDTUHPHGEIFZTAXPVMJUHCKAFOWBIMHBFBVIRQLKOLWYQJKGKFJRUQHPVBZDUARQUKFUTCFUYOHSMWTURCUFHJRDFOWAHORGCUEKWQKFOTZJZARRXPTUQYSAMWSOCVYENBHJNWHBMQKFGYXVAGDGXTSOHBOYXIDWNNHBMQRGCVSZEICVCCQMWUKAVSZFHEMTKOSOSLTULKKVJRCOFBKFOYQZIUVNVJNNLXLXKIGXLXDMHKHCWWRMZQQYCVKFCCTSNZNAXCNQBEVSNUXTRDDZRGKNUQNNRJKGCCTUQGDEHCWWZDZDZXIKNCBFSDSMDEQCFOWBQYZXZVZBXPOIOTZJBIDJKGHBTULKLMBFIPWYGCNFZSCVCQJNEKGQXVYOXPEKWWBFPEUUWUKAWUKAZVBYSYHJKFWERRIJHHWYTSXFFYOSRHHJNNURBNIKYHTULKWRFBBGRKYENBYMZXFBHJNWMIRHXPEKWWMWKFEKXSCHXTLIIKCVXPNNEQKIDYCHFZHEOJXVSODVVJTUZQIMCUGQJRNWRQTUFOGBUQFHUUKFWYRGUMXTBFKFSOEDMKGUHPIONWHCHEZVZDSOFRHJVSFOFUKFZDYACMHGMWHPYOECNNQUFKBIVAQJKGKFEKWYMWTFFBZIXOPMLXVSPCRXMQMLKOOCNNHDPRRDFZWUKAVIRQBYQRBHXPDXRGHBUQWAMSZQTCGQWGQVTUHPPMHBBLZDPCMWZDRDTGBYEDHJKFEKUUCVKAGFHJNWCQTXWKXFVKOLEKDJRDFRHJNWISREOLNNGCJWNWVKZVRRVKMLVNHSWQKFKFPPXPQKRGYYUUHPJRTUHPPMHBKIUBTUTXOSQVHSZIANTBSODCTHCCMWEKOEHECVECGVHJNWVFMQRKGQXVNFQCGCSLFHRXZFDMHPUUCVTUZQMIZQKFRXWGUADLRUUUKFYMRMZQUOOSRHYMFBXSJUFUNXBRNH";

		/*
		String cipheredText = vigenere.cipher(clearText, password);
		System.out.println(cipheredText);


		String decipheredText = vigenere.decipher(secret, password);
		System.out.println(decipheredText);


		textTools.formatText(clearText, true);
		textTools.frequencyAnalysis(secret);
		*/

        //System.out.println("Die ermittelte Länge des Schlüssels durch den Friedmanntest beträgt " + friedmannTest.estimateKeyLength(secret) + " Zeichen");

		/*
		for(int i=0; i<splittedText.length;i++) {
			System.out.println(splittedText[i]);
		}
		*/

        //textTools.frequencyAnalysis(splittedText[7]);

        //System.out.println(kasiskiTest.estimateKeyLength(secret));

		/*
		String test = caesar.shiftText("LYUMATQONMSGQQQEQEMFUMNUOUMZGQZPEQDMQFVQXRAXINZZQQUMQTTFQTQQQYEIINUXTFQDJPQUTYTFQQZDDUZFPQZETUQPUIAMTTMTUTOFQUXLDGIDXDXZXQZHWGLQMQGZZQPADU", vigenere.getVigenereShift('M'));
		System.out.println(test);
		*/

        textTools.frequencyAnalaysisTuple(secret, 2);
        //textTools.frequencyAnalysis(secret);
    }
}